[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
solana-system-interface = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }