[package]
name = "task_scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
serde = { workspace = true }
serde_json = { workspace = true }
engine = { workspace = true }
solana-sdk = { workspace = true }
