[workspace]
resolver = "2"
members = [
    "engine",
    "task_scheduler"
]

[package]
name = "server"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
solana-client = "2.2.0"
solana-sdk = "2.2.0"

[dependencies]
tokio = { workspace = true }
solana-client = { workspace = true }
